#!/bin/bash
_xbps-remove() {
  local prefix="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(printf %s\\n `< ~/.local/share/xbps-completion-installed` |
               awk -v IGNORECASE=1 -v p="$prefix" \
                   'p==substr($0,0,length(p))'))
}
complete -F _xbps-remove -o filenames xbps-remove
